name: languid tuna
favicon: null
layout_spectrum: 0.8099090727046132
typography_spectrum: 0.807566202711314
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.46023785043507814
  lightness: 0.2699605864472687
  saturation: 0.47831104532815516
  rhythmicContrast: 0.8593653833959252
purpose: []
